### ISSUE TITLE
QA - Site - Registration - User can not be able to register new user.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-service-apis#137]
QA - Site - Registration - User can not be able to register new user.

Open url.
click on login.
click on New user? Link.
Fill Proper Data and click on Register.

![user can not be able to register new user](https://user-images.githubusercontent.com/36226408/36656704-999020c6-1aef-11e8-903d-c9a926c41d65.jpg)

**Comment by priyank26** [comment]
I changed validation message in dynamic form as per api response.

**Comment by Nikunj025** [comment]
Done
