### ISSUE TITLE
QA - Site - Product Detail Page - Product Qty field is occur multiple time if user try to multiple click on Product Color Swatches.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#142]
QA - Site - Product Detail Page - Product Qty field is occur multiple time if user try to multiple click on Product Color Swatches.

![product qty field is occur multiple time if user try to multiple click on product color swatches](https://user-images.githubusercontent.com/36195435/36658344-20743a68-1af6-11e8-8c54-b275c9b79c06.jpg)

**Comment by qajha** [comment]
Still Issue is not resolved if product not have any product color.

**Comment by Jignasha22** [comment]
resolved.

**Comment by nnpatel** [comment]
It is resolved and now product color field is mandatory while importing data to pdm.

**Comment by Nikunj025** [comment]
Done
