### ISSUE TITLE
QA - Site - Product Detail Page - Delete option of qty box is not working.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#143]
QA - Site - Product Detail Page - Delete option of qty box is not working.

User can not be able to Delete Qty field.

![delete option of qty box is not working](https://user-images.githubusercontent.com/36195435/36658425-7859a83a-1af6-11e8-8b53-b4f8264af077.jpg)

**Comment by Jignasha22** [comment]
resolved.

**Comment by Nikunj025** [comment]
Done.

Its Working Fine now.
