### ISSUE TITLE
QA - Site - Product Detail Page - Entered Qty Display in Shipping Section instead of NaN.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#145]
QA - Site - Product Detail Page - Entered Qty Display in Shipping Section instead of NaN.

![qty display in shipping section instead of nan](https://user-images.githubusercontent.com/36195435/36660103-e4469ee4-1afc-11e8-981c-f9654df5629a.jpg)

**Comment by Jignasha22** [comment]
Resolved.

**Comment by qajha** [comment]
Done.
