### ISSUE TITLE
QA - Site - Product Detail Page - Shipping Estimator is not working.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#150]
QA - Site - Product Detail Page - Shipping Estimator is not working.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Click on Shipping Estimator options.
Observe its not working.

![shipping estimator is not working](https://user-images.githubusercontent.com/36195435/36725745-4ec2b006-1bdd-11e8-9ea0-7410e2cae5a7.jpg)

**Comment by Jignasha22** [comment]
Right now we remove this icon.

**Comment by qajha** [comment]
Issue is resolved now in QA server
