### ISSUE TITLE
QA - Site - Product Detail Page - Place order functionality is not working.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#151]
QA - Site - Product Detail Page - Place order functionality is not working.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order and fill the data.
Click on Add to Cart Button.
Observe its not working.

![place order is not working](https://user-images.githubusercontent.com/36195435/36726018-460e5f18-1bde-11e8-8247-f002a93ea402.jpg)

**Comment by nnpatel** [comment]
It is resolved and now product color field is mandatory while importing data to pdm.

**Comment by Nikunj025** [comment]
Still User not able to do place order if Product Color is not available.

Try with below Product.

http://5a8d53d62e764f0014b13cf2.469a8b30-2cc4-4f79-ab0b-d92263c098b0.flowzqa.tk/productdetail.html?locale=en_us&pid=289935d0-17e1-11e8-9430-33823179521a

**Comment by Nikunj025** [comment]
Done
