### ISSUE TITLE
QA - Site - Product Detail Page - User can not be able to Select Shipping Address in Place Order.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#152]
QA - Site - Product Detail Page - User can not be able to Select Shipping Address in Place Order.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter Qty in Qty box.
Select Shipping Method.
Observe its not working.

![user can not be able to select shipping address in place order](https://user-images.githubusercontent.com/36195435/36726154-d23c330c-1bde-11e8-82f1-15a5bb60cb3c.jpg)

**Comment by Nikunj025** [comment]
Done.

User Should be Able to Select Shipping Section Now.
