### ISSUE TITLE
QA - Site - Product Detail Page - User Can not Getting City Name in Dropdown List.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#155]
QA - Site - Product Detail Page - User Can not Getting City Name in Dropdown List.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter Qty in Qty box.
Select Shipping Address and Click on Address Book List Button.
Click on Add Address button.
Fill Data till City Field.
Observe data not getting in City dropdown.

![user can not getting city name in dropdown list](https://user-images.githubusercontent.com/36195435/36729909-b72b8f2e-1beb-11e8-8b28-c5b750dc4e2c.jpg)

**Comment by qajha** [comment]
Right now some data is populate from API in city field as per discussion with dev team

**Comment by Nikunj025** [comment]
Done.
