### ISSUE TITLE
QA - Site - Product Detail Page - Shipping Section - Shipping Address Search icon is not working in Shipping Section.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#161]
QA - Site - Product Detail Page - Shipping Section - Shipping Address Search icon is not working in Shipping Section.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter Qty in Qty box.
Select Shipping Address.
Click on Search icon.

![shipping address search icon is not working in shipping section](https://user-images.githubusercontent.com/36195435/36769582-1382a012-1c6b-11e8-9035-a0c48e089aae.jpg)

**Comment by priyank26** [comment]
This search icon is for display purpose. I removed cursor icon.

**Comment by Nikunj025** [comment]
Done.
Icon Removed Now.
