### ISSUE TITLE
QA - Site - Product Detail Page - Shipping Section - Add New Address - Success Message need to Change on Save New Address.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#165]
QA - Site - Product Detail Page - Shipping Section - Add New Address - Success Message need to Change on Save New Address.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter Qty in Qty box.
Select Shipping Address.
Click on Add New Address Button.
Fill Proper data and Observe Success Message.

![success message need to change on save new address](https://user-images.githubusercontent.com/36195435/36769979-ab608942-1c6d-11e8-81d4-b020444bd832.jpg)

**Comment by qajha** [comment]
Done

**Comment by qajha** [comment]
Double dot display in Success Alert Message on Address Book Page.

![double dot display in success alet message on address book page](https://user-images.githubusercontent.com/36195435/37195678-e024f7de-2399-11e8-979e-73bbd0f57bf1.jpg)

**Comment by Nikunj025** [comment]
Done
