### ISSUE TITLE
QA - Site - Product Cart Page - Size and Quantity are not display on cart page.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#169]
QA - Site - Product Cart Page - Size and Quantity are not display on cart page.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab.
Fill all data and go to cart page.
Observe Size & Quantity is missing.

![size and qty are not display on cart page](https://user-images.githubusercontent.com/36195435/36771391-2225f0a0-1c76-11e8-8b90-4d99dc1f40e5.jpg)

**Comment by Nikunj025** [comment]
Done.

Price table Display Now in that Section and We Change Label Name "Quantity" instead of "Size and Quantity".
