### ISSUE TITLE
QA - Site - Item Code should be display as uniformly in Complete site.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#170]
QA - Site - Item Code should be display as uniformly in Complete site.

![item code should be display as uniformly in complete site](https://user-images.githubusercontent.com/36195435/36771504-d5cb5e2e-1c76-11e8-9c94-f3f2b7eb7030.jpg)

![item code should be display as uniformly in complete site 1](https://user-images.githubusercontent.com/36195435/36771503-d57f6082-1c76-11e8-9bdf-69454253a4cd.jpg)

**Comment by Nikunj025** [comment]
Done
