### ISSUE TITLE
QA - Site - Product Detail Page - Validation message needs to change for minimum quantity.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#175]
QA - Site - Product Detail Page - Validation message needs to change for minimum quantity.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter less than minimum Qty in Qty box.
Fill other data and click on Add to cart button.

![validation message needs to change for minimum quantity](https://user-images.githubusercontent.com/36195435/36772886-104ccd2a-1c7d-11e8-9dcf-283b4d843b36.jpg)

**Comment by Nikunj025** [comment]
Not Able to Check Minimum qty Validation on Detail Page.

**Comment by priyank26** [comment]
This issue was resolved but because of some other issue we are getting problem in place order. Now it's working.

**Comment by Nikunj025** [comment]
Done. Validation Message Changed Now.
