### ISSUE TITLE
QA - Site - Product Detail Page - Place Order - Alert message should not be display after click on Add to cart button.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#178]
Alert message should not be display after click on Add to cart button.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter Qty in Qty box.
Select Shipping Address.
Fill the Data and click on add to cart button.
Observe Success Message display after click on Add to Cart Button.

No Success message should be display if Page is redirect to cart Page.

![alert message should not be display after click on add to cart button](https://user-images.githubusercontent.com/36195435/36774605-ca6651d4-1c84-11e8-8b1b-8cad26a114d6.jpg)

**Comment by qajha** [comment]
Still Alert Message is display when user click on Add to cart button from Detail Page.

**Comment by Nikunj025** [comment]
Done
