### ISSUE TITLE
QA - Site - Cart Page - Delete popup Text Should be Proper on Cart Page.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#180]
QA - Site - Cart Page - Delete popup Text Should be Proper on Cart Page.

Go To Publish website.
Click on search button and go to search page.
Add Multiple Product in Cart Page.
Now Click on Delete Product option on cart page.
Observe Delete popup message popup.

![delete popup text should be proper on cart page](https://user-images.githubusercontent.com/36195435/36774863-c08d79ca-1c85-11e8-8139-5f36e9775883.jpg)

**Comment by Nikunj025** [comment]
Done
