### ISSUE TITLE
QA - Site - Checkout Page - Total Price Text label is  on Page.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#181]
QA - Site - Checkout Page - Total Price Text label is  on Page.

Go To Publish website.
Click on search button and go to search page.
Add Multiple Product in Cart Page.
Click on Checkout button and go to Checkout Page.
Observe Total Price Text is Missing.

![total price text label is missing](https://user-images.githubusercontent.com/36195435/36775047-6431966a-1c86-11e8-9d96-edc0a1e8b9db.jpg)

**Comment by nnpatel** [comment]
Form submit on click of back button is also resolved.

**Comment by qajha** [comment]
Done
