### ISSUE TITLE
QA - Site - Product Cart Page - If Data not available then Label Should not be display.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#183]
QA - Site - Product Cart Page - If Data not available then Label Should not be display.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter Qty in Qty box.
Click on Add to Cart Button.
Observe Size & Qty Block.

![if data not available then label should not be display](https://user-images.githubusercontent.com/36195435/36775547-88bd4342-1c88-11e8-8ca1-ea3dea400a3c.jpg)

**Comment by Nikunj025** [comment]
Done.

Now If Data Not available then Label also not display.
