### ISSUE TITLE
QA - Site - My Acc - View Order - Need to Proper Alignment of View Order Page.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#184]
QA - Site - My Acc - View Order - Need to Proper Alignment of View Order Page.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Place One Order.
Now Click on View Order Page.
Click on View Button From Order List.

![need to proper alignment of view order page](https://user-images.githubusercontent.com/36195435/36775888-d9dccad0-1c89-11e8-94b7-5c65472884a6.jpg)

**Comment by Nikunj025** [comment]
Done.

Looking Fine Now.
