### ISSUE TITLE
QA - Site - Product Cart Page - Product Color Swatch is display wrong on Cart Page.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#188]
QA - Site - Product Cart Page - Product Color Swatch is display wrong on Cart Page.

Go To Publish website.
Enter 44450 in Search textbox.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter Qty in Qty box.
Click on Add to Cart Button.
Observe Product Color Swatches are wrong display.

![product color swatch is display wrong on cart page](https://user-images.githubusercontent.com/36195435/36779305-9130c5c8-1c95-11e8-88f0-8650de309b78.jpg)

**Comment by nnpatel** [comment]
Color name is going to display.

**Comment by qajha** [comment]
Done.
Product Color Name display now.
