### ISSUE TITLE
QA - Site - My Acc -Order List Page - View Order - Product Color Swatch are display wrong on View Order Page.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#189]
QA - Site - Order List Page - View Order - Product Color Swatch are display wrong on View Order Page.

Go To Publish website.
Enter 44450 in Search textbox.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter Qty in Qty box.
Click on Add to Cart Button and place order.
Click on View Order Button.
Click on View option for Your order.
Observe Product Color Swatches are wrong display.

![product color is display wrong in order view](https://user-images.githubusercontent.com/36195435/36779772-194059aa-1c97-11e8-8029-25a192d4f992.jpg)

**Comment by nnpatel** [comment]
Color name is going to display.

**Comment by qajha** [comment]
Product Color Name display now instead of Swatches.
