### ISSUE TITLE
QA - Site - Home Page - User not able to logout.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/website-service-apis#192]
QA - Site - Home Page - User not able to logout.

If user is logged in related Modules like crm, web builder, uploader with registered user but that user are not registered on Created Website then Undefined text is display there.

Now User Text Display and user not able to logout.

![user not able to logout](https://user-images.githubusercontent.com/36226408/36827423-7a6cd440-1d39-11e8-99e9-a294789dcc12.jpg)

**Comment by Nikunj025** [comment]
Still not resolved if user login with cred in another modules.

**Comment by priyank26** [comment]
Please clear old cookies and local storage. Then check.

**Comment by qajha** [comment]
User is not do the delete the cookies from browser everytimes so we need provide any solution for this Issue.

**Comment by Nikunj025** [comment]
Still issue is not resolved.
Already discuss with Priyank and Neel, Regarding this issue.

**Comment by Nikunj025** [comment]
Done
