### ISSUE TITLE
QA - Site - Product Detail Page - Suggestion box of Address is not still display if user click another Field.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#194]
QA - Site - Product Detail Page - Suggestion box of Address is not still display if user click another Field.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter Qty in Qty box.
Select Shipping Address.
Enter Some text for Address Search now click on Shipping Radio button.

![search address in shipping](https://user-images.githubusercontent.com/36195435/36829044-4136e18e-1d43-11e8-83ba-1501710a7391.jpg)

Test Scenarios
***************
1. Search Suggestion Dropdown display properly.
2. Suggestion Dropdown should be disappear if user remove all the data from Search textbox.

**Comment by Nikunj025** [comment]
Still Not Resolved.

**Comment by nnpatel** [comment]
As per the communication with Nikunj, all the possible changes are done by Divyesh, and Nikunj will check it once we move it to QA.

**Comment by Nikunj025** [comment]
Done
