### ISSUE TITLE
QA - Site - Product Detail Page - Data overwrite on dropdown on detail page.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#211]
QA - Site - Product Detail Page - Data overwrite on dropdown on detail page.

![data overwrite on dropdown on detail page](https://user-images.githubusercontent.com/36195435/37195268-1b183e3e-2398-11e8-9c05-e34e172da725.jpg)

**Comment by Nikunj025** [comment]
Done
