### ISSUE TITLE
QA - Site - Product Detail Page - Shipping Section - Edit Address - User can not be able to update type in Edit Address.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#212]
QA - Site - Product Detail Page - Shipping Section - Edit Address - User can not be able to update type in Edit Address.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter Qty in Qty box.
Select Shipping Address.
Click on Address Book List Button.
Edit any Address.
Change type. like Is Office to to Home.
Save it and Edit address again.
Check its type its not updated.

![user can not be able to update type in edit address](https://user-images.githubusercontent.com/36195435/37196782-1cdf628c-239e-11e8-9a04-a040cc73189a.jpg)

**Comment by Nikunj025** [comment]
Done
