### ISSUE TITLE
QA - Site - Product Detail Page - User Can not be add Product in Cart Page

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#213]
QA - Site - Product Detail Page - User Can not be add Product in Cart Page.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter Qty in Qty box.
Select Shipping Address.
Fill Proper Detail and Click on Add to Cart Button.

![user can not be add product in cart page](https://user-images.githubusercontent.com/36195435/37196910-9906689c-239e-11e8-994c-296b1cd20e60.jpg)

**Comment by Nikunj025** [comment]
Done.

Its Working Now.
