### ISSUE TITLE
QA - Site - Product Detail Page - Product qty Should be Change in Shipping Section if user change in Main Qty Box.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#214]
QA - Site - Product Detail Page - Product qty Should be Change in Shipping Section if user change in Main Qty Box.

Go To Publish website.
Click on search button and go to search page.
Click on any product and go tot detail page.
Select Place Order tab and Select product Color.
Enter Qty in Qty box.
Select Shipping Address.
Now Change qty in Main Qty box.
Observe Qty not change din Shipping section automatically.

![product qty should be chnage in shipping section if user change in main qty box](https://user-images.githubusercontent.com/36195435/37197209-e1577e50-239f-11e8-8c6a-603e0b60f7ec.jpg)

**Comment by Nikunj025** [comment]
Done
