### ISSUE TITLE
QA - Site - Internal Server Error on Change Password Page.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/website-service-apis#216]
QA - Site - Internal Server Error on Change Password Page.

Internal Server Error display if user wrong Current pwd and try to change it.

![internal server error](https://user-images.githubusercontent.com/36195435/37198316-e82df430-23a3-11e8-85ae-a8ba0edc8f4b.png)

**Comment by Nikunj025** [comment]
Done
